### PR TITLE
8442 build bp pyrsl

### PR DESCRIPTION
**Pull request by keithbrown**

### CODE REVIEW

**Comment by john-tornblom** [comment]
I have several issues with this PR.

1) the warning about schema mismatch is intentional, hiding errors does not magically fix them.
2) removing the NULL classification heuristics break the relate/unrelate logic
3) The PR shall be rebased and all "undo" commits shall be squashed

**Comment by keithbrown** [comment]
1) You are of course right.  I had commented those out because the error messages were overwhelming my log and I was having a hard time seeing the good data.  I need to add the message back in.  Perhaps we could just flag an error on each first bad insert into a table.  That way the user would still get an error warning without getting overwhelmed with many duplicate error messages.

**Comment by keithbrown** [comment]
Regarding 2, the issue #4 captures the reason for this change.  It is simply for backwards compatibility with the behavior with old generator.   

Maybe we can update all the PEI data.  Not sure, but I prefer to use the backwards compatibilty approach first so we can continue getting rid of old generator rather than stopping that project completely while the PEI data is upgraded.

**Comment by john-tornblom** [comment]
I'm closing this issue due to inactivity. You can reopen it and address comments if this is still needed.

**Pull request closed without merging**
