### PR TITLE
job #42 assure 'Label' gets set for state machine actions and bridge …

### PR DESCRIPTION
**Pull request by leviathan747**
…actions

See #42

### CODE REVIEW

**Comment by leviathan747** [comment]
This update has been published in pre-release [v2.3.1a1](https://github.com/xtuml/pyxtuml/releases/tag/v2.3.1a1)

**Comment by john-tornblom** [comment]
Back in the day, I envisioned this as a derived attribute, defined using an action language that is interpreted.
I'm busy with other things, but will look at this in a couple of weeks.

**Comment by leviathan747** [comment]
@john-tornblom that would be nifty, however I think unnecessary. The implementation here follows the BridgePoint pre-builder for the most part with a couple key differences:
- Full element paths are used (BP pre-build only includes the direct parent for elements)
- For transitions, a longer form label is employed in the format `<start state> [<event name>] -> <end state>`. BP only uses the event name (which is not enough to uniquely identify the transition...). The end state is not strictly needed to guarantee uniqueness, but I'm using this for generating trace logging statements, so it was advantages to create a label that is readable for debugging.

I also fixed a bug where "no event transitions" would cause pre-build to crash (I guess it's debatable whether or not this is a bug or not...)

**Comment by leviathan747** [comment]
It has been over a year and I have been using this successfully in Ciera. I am going to approve/merge it.

**Pull request merged**
