### PR TITLE
update schema to base timestamp on integer

### PR DESCRIPTION
**Pull request by leviathan747**
Recent changes to BridgePoint have made timestamp based on integer and not inst<Mapping>. Update the pyxtuml schema to reflect this.

### CODE REVIEW

**Comment by john-tornblom** [comment]
Do you think this change introduces incompatibility issues?

**Comment by leviathan747** [comment]
I do not believe so. @cortlandstarrett might have more to say, but without having intimate knowledge about the other MC's out there, I do not believe it will have large negative effects.

**Comment by cortlandstarrett** [comment]
We have now made this change in BridgePoint proper.  So, any impact on
downstream tooling will need to occur anyway.  I like keeping BP prebuilder
and pyxtuml prebuilder aligned.

**Comment by john-tornblom** [comment]
Sure, but this changes complicates the maintenance, and motivates a major version bump of pyxtuml.
It would be nice to be able to support both to some extent, the .xtuml files contains version-info (prefixed with "persistence-version: "), but will be somewhat hacky imho. 

What was the motivation behind this change? I never really liked having both timer handling and time in the same EE to begin with. The OAL language has syntax for handling timers, just not implemented in bridgepoint (see Executable UML: A Foundation for Model-driven Architecture for examples).

**Comment by cortlandstarrett** [comment]
https://onefact.net/2020/05/12/panda-open-source-development/

https://github.com/xtuml/bridgepoint/blob/master/doc-bridgepoint/notes/11937_epoch/11937_epoch_ant.adoc

The above two links give the background.  The even shorter answer is "time
arithmetic".  String is pretty weak in that regard.

**Comment by john-tornblom** [comment]
Right. I would just have made a new package with EE+UserType out of this. I have several examples of similar stuff at: https://github.com/john-tornblom/mc_stdlib, working fine in both verifier and mc3020.

But if you really feel the need to break backwards compatibility, I'll merge this.

**Comment by cortlandstarrett** [comment]
The change in MC-3020 is trivial.  I vote we make this Right (numeric
rather than string).

**Comment by john-tornblom** [comment]
Okey, but where does strings fit in to this?

**Comment by cortlandstarrett** [comment]
String is the former core type for the timestamp UDT.

**Comment by john-tornblom** [comment]
Hmmm, isn't it `inst<Mapping>??`

**Comment by cortlandstarrett** [comment]
Well, yes, inst_ref<Mapping>, which just meant, "special case this anywhere
you see it".

**Comment by john-tornblom** [comment]
So, can the `date` type also be update? Then, could `inst_ref<Mapping>` be removed/deprecated?

**Comment by cortlandstarrett** [comment]
That would be feasible.  But typically date types are structural, while a
timestamp is typically an integer referenced from some 'epoch'.  We did not
change the handling of 'date'.

**Comment by john-tornblom** [comment]
Yea, UNIX time can be captured by an integer, but it is not unusual with other representation of date and time, see, e.g., https://docs.python.org/3/library/datetime.html (object) and https://docs.python.org/3/library/time.html#time.clock_settime (64bit floating point number)

**Comment by john-tornblom** [comment]
Lets merge this into a version 3 branch, but also make sure we address related issues that might appear down the line before a stable major version bump appears on master. Sounds OK?

**Comment by cortlandstarrett** [comment]
That sounds good to me.

**Comment by john-tornblom** [comment]
Install with: `python -m pip install git+https://github.com/xtuml/pyxtuml.git@develop/v3.0`

**Pull request merged**
