### PR TITLE
Add ooaofgraphics to schema

### PR DESCRIPTION
**Pull request by leviathan747**

### CODE REVIEW

**Comment by john-tornblom** [comment]
Hmm, why is this needed?

**Comment by leviathan747** [comment]
@john-tornblom I want to use pyxtuml to do some model upgrade tasks. The flow would be:

1. Load a BridgePoint model
2. Traverse the instances and perform upgrades
3. Persist the instances to an `.xtuml` file
4. Load the model back into BridgePoint using the single file model import utility

I don't want to have to re-layout my diagrams after upgrade.

**Comment by leviathan747** [comment]
By the way, the majority of changes I have made to this repository are changes in the `bridgepoint` module (specifically prebuild). Do you think at some point it would make sense to separate that module into its own project? `pyxtuml` itself is more generic and it seems a bit as though it is mixing two different things.

**Comment by john-tornblom** [comment]
> By the way, the majority of changes I have made to this repository are changes in the `bridgepoint` module (specifically prebuild). Do you think at some point it would make sense to separate that module into its own project? `pyxtuml` itself is more generic and it seems a bit as though it is mixing two different things.

Yea, that makes sense, I initially had a pyoal package, but merged that with pyxtuml for convenience (since no other action language was supported by bridgepoint at that time). I would wait until we have a candidate python prebuilder, e.g. MASL. Its difficult to design a good API with only one API user...

**Comment by john-tornblom** [comment]
Regarding ooaofgraphics. I wonder if this will impact performance or not, and if the graphics parameters introduced by this PR are required or optional? For example, If I have handcrafted instances without graphics, would that still be possible to execute in the oal interpreter?

**Comment by leviathan747** [comment]
> Regarding ooaofgraphics. I wonder if this will impact performance or not, and if the graphics parameters introduced by this PR are required or optional? For example, If I have handcrafted instances without graphics, would that still be possible to execute in the oal interpreter?

I'll do some performance tests. Note that the change to the usage here is in the schema generator itself and not in prebuild. If you tried to load/parse a model without graphical instances, it would load the schema from `schema.py` (including the definitions of the tables for graphical instances), but when it loaded the model data there would be no difference

**Comment by john-tornblom** [comment]
Ahh, sorry, only schema gen, I thought it was in the prebuilder (reading of my phone). I withdraw that comment :)

**Comment by leviathan747** [comment]
Regarding performance, there is functionally no difference. I did a back to back test on a large model and saw no degradation of performance.

But now that I'm thinking about this, I realized something that makes me think I should withdraw this PR... `pyxtuml` automatically create new tables for any instances that it encounters and cannot find a metaclass for. I just did a quick test and confirmed that even without this change, if I load a model with graphical instances and then serialize the graphical instances are persisted. My original concern of losing graphics was unfounded!

Including graphics in the BridgePoint schema might at some point make sense, but at the moment I think it's completely superfluous so I am going to close the PR.

**Comment by john-tornblom** [comment]
Ah yes, instances of unknown classes will be persisted, but attributes of such instances are 'anonymous'. 
If you need to access these attributes using pyxtuml, they are named '_i', where i is an index in the schema attribute list.

**Pull request closed without merging**
